import {json} from 'react-router';

/**
 * Dynamic robots.txt route
 * This provides a fallback and can be customized per environment
 */
export async function loader({request}) {
  const url = new URL(request.url);

  const robotsTxt = `# robots.txt for vastara.online
# Generated by Hydrogen

# Allow all crawlers
User-agent: *
Allow: /

# Disallow admin and account areas
Disallow: /account
Disallow: /admin
Disallow: /cart
Disallow: /checkout
Disallow: /search
Disallow: /recommendations
Disallow: /cart.js
Disallow: /cart/update.js
Disallow: /recommendations/products

# Crawl-delay (optional)
Crawl-delay: 1

# Sitemap
Sitemap: ${url.origin}/sitemap.xml
`;

  return new Response(robotsTxt, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  });
}
